#!/usr/bin/env python
"""Issue mTLS client certs for the simulator's VIN-hash shards, plus one for
the ingest-gateway, and generate the Mosquitto ACL file that binds each
shard's cert to its own topic segment.

Why shards and not one cert per vehicle: PLAN §2 shards Mosquitto by VIN
hash, and this script gives each shard exactly one client identity rather
than provisioning ~100K live device certs in a single hackathon session (see
`libs/fleetcore/algorithms/sharding.py` for the full rationale and the
matching VIN->shard function the simulator and ingest-gateway both use).

Idempotent: skips a shard whose cert already exists, so re-running after
raising MQTT_SHARD_COUNT only issues the new ones.

Usage: python infra/certs/issue-shard-certs.py [n_shards]
(defaults to MQTT_SHARD_COUNT from .env, or 32)
"""
from __future__ import annotations

import datetime
import os
import sys
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

CERT_DIR = Path(__file__).resolve().parent
CA_DIR = CERT_DIR / "ca"
SHARDS_DIR = CERT_DIR / "issued" / "shards"
ACL_PATH = Path(__file__).resolve().parents[1] / "compose" / "mosquitto.acl"

DAYS_VALID = 825


def _load_ca() -> tuple[x509.Certificate, rsa.RSAPrivateKey]:
    ca_cert = x509.load_pem_x509_certificate((CA_DIR / "ca.crt").read_bytes())
    ca_key = serialization.load_pem_private_key((CA_DIR / "ca.key").read_bytes(), password=None)
    return ca_cert, ca_key


def _issue(cn: str, out_dir: Path, ca_cert: x509.Certificate, ca_key: rsa.RSAPrivateKey) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    key_path, crt_path = out_dir / f"{cn}.key", out_dir / f"{cn}.crt"
    if crt_path.exists():
        return

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    subject = x509.Name([
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "FleetPulse Dev"),
        x509.NameAttribute(NameOID.COMMON_NAME, cn),
    ])
    now = datetime.datetime.now(datetime.timezone.utc)
    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(ca_cert.subject)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - datetime.timedelta(days=1))
        .not_valid_after(now + datetime.timedelta(days=DAYS_VALID))
        .sign(ca_key, hashes.SHA256())
    )

    key_path.write_bytes(
        key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=serialization.NoEncryption(),
        )
    )
    crt_path.write_bytes(cert.public_bytes(serialization.Encoding.PEM))


def _write_acl(n_shards: int) -> None:
    lines = [
        "# Generated by infra/certs/issue-shard-certs.py — do not hand-edit.",
        "# use_identity_as_username (mosquitto.conf) makes the client cert CN the MQTT username.",
        "",
        "user ingest-gateway",
        "topic read fleet/#",
        "",
    ]
    for shard in range(n_shards):
        lines += [
            f"user shard-{shard}",
            f"topic write fleet/+/shard-{shard}/+/telemetry",
            "",
        ]
    ACL_PATH.parent.mkdir(parents=True, exist_ok=True)
    ACL_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    n_shards = int(sys.argv[1]) if len(sys.argv) > 1 else int(os.environ.get("MQTT_SHARD_COUNT", 32))
    if not (CA_DIR / "ca.key").exists():
        raise SystemExit("Dev CA not found — run infra/certs/generate-dev-certs.sh first.")

    ca_cert, ca_key = _load_ca()
    for shard in range(n_shards):
        _issue(f"shard-{shard}", SHARDS_DIR, ca_cert, ca_key)
    _issue("ingest-gateway", CERT_DIR / "issued", ca_cert, ca_key)
    _write_acl(n_shards)
    print(f"Issued/verified {n_shards} shard certs + ingest-gateway cert. ACL written to {ACL_PATH}.")


if __name__ == "__main__":
    main()
