{{- range $name, $svc := .Values.services }}
{{- if $svc.port }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleetpulse.serviceName" (dict "root" $ "name" $name) }}
  labels:
    {{- include "fleetpulse.labels" (dict "root" $ "name" $name) | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
---
{{- end }}
{{- end }}
